# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dataframeviz',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/dataframeviz',
                'lib_path': 'dataframeviz'},
  'syms': {'dataframeviz.core': {'dataframeviz.core.foo': ('core.html#foo', 'dataframeviz/core.py')}}}
